name: diskann_memory
constraints:
  build: cuvs_bench.constraints.diskann_memory_build_constraints
  # search: cuvs_bench.constraints.diskann_memory_search_constraints
groups:
  base:
    build:
      R: [64, 96]
      L_build: [64, 128, 256, 384]
      alpha: [1.0, 1.2]
      use_cagra_graph: [False]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]
  cagra:
    build:
      cagra_graph_degree: [32, 64, 96]
      cagra_intermediate_graph_degree: [64, 96, 128]
      use_cagra_graph: [True]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]