name: diskann_ssd
constraints:
  build: cuvs_bench.config.algos.constraints.diskann_ssd_build
groups:
  base:
    build:
      R: [64, 96]
      L_build: [64, 128, 256, 384]
      QD: [192]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]