name: diskann_ssd
constraints:
  build: cuvs_bench.config.algos.constraints.diskann_ssd_build
groups:
  base:
    build:
      R: [64, 96]
      L_build: [64, 128, 256, 384]
      use_cagra_graph: [False]
      QD: [192]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]
  cagra:
    build:
      R: [32, 64, 96]
      cagra_intermediate_graph_degree: [64, 96, 128]
      use_cagra_graph: [True]
      QD: [192]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]